name: Build and push docker image
on: push
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install
      - run: npm test
      - run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: openemp/dashboard-ui:latest
